# You can write down any information and it will be available
# at the address /api/info2 (if you use default nginx config).
# If server.host (str) will be defined then this value
# will be displayed in the web interface.

server:
    host: "@auto"
