# You can write down any information and it will be available
# at the address /api/info2 (if you use default nginx config).
# To change PiKVM's hostname, use "hostnamectl hostname <new>".

server:
    host: "@auto"
